# fly.toml app configuration file generated for booking on 2024-06-15T04:15:47-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'booking'
primary_region = 'nrt'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'

[env]
  TZ = 'Asia/Tokyo'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
